export function getReceivedEmailTemplate( fullName: string, email: string, phone: string, comments: string ): string {
  return `
  <!DOCTYPE html><html lang="en"><head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>New Contact Message</title> <style> /* General reset */ body { margin: 0; padding: 0; font-family: Arial, sans-serif; color: #333333; } table { border-spacing: 0; border-collapse: collapse; margin: 0 auto; } img { max-width: 100%; height: auto; } /* Container styles */ .email-container { max-width: 800px; margin: 0 auto; width: 100%;} .logo-container { text-align: center; margin-bottom: 20px; } .title { font-size: 24px; font-weight: bold; text-align: center; margin: 20px 0; } .content { font-size: 16px; line-height: 1.5; text-align: left; padding: 0 60px; } .content p { margin: 10px 0; } .footer { margin: 20px 0; text-align: center; font-size: 14px; color: #888888; } .header-email { background-color: #0A0A20; color: #fff; text-align: center; padding: 20px 0; } </style></head><body> <table role="presentation" width="100%"> <tr> <td class="header-email"> <img src="https://res.cloudinary.com/dq6txmetn/image/upload/v1732298324/dynamic-studio/logo-dynamic-studio-dark-bg_tvcttx.png" alt="Dynamic Studio" /> </td> </tr> </table> <table role="presentation" width="100%"> <tr> <td align="center"> <!-- Email Container --> <table class="email-container"> <!-- Title Section --> <tr> <td class="content"> <h1 class="title">New Contact Message</h1> </td> </tr> <!-- Content Section --> <tr> <td class="content"> <p><strong>Name:</strong> ${ fullName }</p> <p><strong>Email:</strong> ${ email }</p> <p><strong>Phone:</strong> ${ phone }</p> <p><strong>Message:</strong></p> <p>${ comments }</p> </td> </tr> <!-- Footer Section --> <tr> <td class="footer"> <p>&copy; 2024 Dynamic Studio. All rights reserved.</p> </td> </tr> </table> </td> </tr> </table></body></html>
  `
}

export function getConfirmationEmailTemplate( fullName: string ): string {
  return `
  <!DOCTYPE html><html lang="en"><head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Thank You for Your Message!</title> <style> /* General reset */ body { margin: 0; padding: 0; font-family: Arial, sans-serif; color: #333333; } table { border-spacing: 0; border-collapse: collapse; margin: 0 auto; } img { max-width: 100%; height: auto; } /* Container styles */ .email-container { max-width: 800px; margin: 0 auto; width: 100%;} .logo-container { text-align: center; margin-bottom: 20px; } .title { font-size: 24px; font-weight: bold; text-align: center; margin: 0 0 10px; } .subtitle { font-size: 18px; font-weight: 600; text-align: center; margin: 0 0 20px; color: #555555; } .content { font-size: 16px; line-height: 1.5; text-align: left; padding: 0 60px; } .content p { margin: 10px 0; } .footer { margin: 20px 0; text-align: center; font-size: 14px; color: #888888; } .header-email{ background-color: #0A0A20; color: #fff; text-align: center; } </style></head><body> <table role="presentation" width="100%"> <tr> <td class="header-email"> <br> <br> <img src="https://res.cloudinary.com/dq6txmetn/image/upload/v1732298324/dynamic-studio/logo-dynamic-studio-dark-bg_tvcttx.png" alt="Dynamic Studio" /> <br> <br> <br> </td> </tr> </table> <table role="presentation" width="100%"> <tr> <td align="center"> <!-- Email Container --> <table class="email-container"> <!-- Title Section --> <tr> <td class="content"> <br> <br> <h1 class="title">Thank You for Your Message!</h1> <h2 class="subtitle">We’ve Received Your Submission</h2> </td> </tr> <!-- Content Section --> <tr> <td class="content"> <p>Hello, ${  fullName  }</p> <p> Thank you for reaching out to us! We’ve received your message and will get back to you as soon as possible. If your inquiry is urgent, feel free to contact us directly through our <a href="tel:(837) 233-6612" style="color: #3CDC00;">(837) 233-6612</a> or <a href="mailto:contact@dynamicstudio.us" style="color: #3CDC00;">contact@dynamicstudio.us</a>. </p> <p>We appreciate your patience and look forward to assisting you.</p> <p>Best regards,</p> <p><strong>Dynamic Studio</strong></p> </td> </tr> <!-- Footer Section --> <tr> <td class="footer"> <br> <br> <br> <p>&copy; 2024 Dynamic Studio. All rights reserved.</p> <br> </td> </tr> </table> </td> </tr> </table></body></html>
  `
}